name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v3
      with:
        version: 10.12.4
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Run type check
      run: pnpm type-check

    - name: Run linter
      run: pnpm lint

    - name: Run tests
      run: pnpm test

    - name: Build all packages
      run: pnpm build

    - name: Run tests with coverage
      run: pnpm test:coverage

    # - name: Upload coverage reports to Codecov
    #   uses: codecov/codecov-action@v3
    #   if: matrix.node-version == '20.x'
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     flags: unittests
    #     name: codecov-umbrella
    #     fail_ci_if_error: false